name: Terraform CI/CD

on:
  push:
    branches: [ main ]

jobs:
  plan:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::523473407799:role/Gitrole
          aws-region: eu-west-1

      - name: Terraform Init
        run: terraform init -reconfigure
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform

  apply:
    needs: plan
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::523473407799:role/Gitrole
          aws-region: eu-west-1

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform
